<?php

### This file has been generated by webmerge ###
### Do not change anything in here, it will be lost ###

### BEGIN OF CLASS tx_rtpwebmerge_embed_data ###

class tx_rtpwebmerge_embed_data {

	// precreated include file by webmerge
	private static $includes = %%includes%%;

	// load the include file
	private static function getInclude($file) {

		$html = file_get_contents($file);

		if ($html !== FALSE) { return $html; }

		return sprintf('<!-- rtp_webmerge failed including %s -->', htmlspecialchars($file));

	}

	// select domain id from the configured pages
	public static function select($rootline) {

		foreach ($rootline as $pid) {

			foreach (self::$includes as $did => $include) {

				if ($pid == $did) { return $did; }

			}

		}

		$array = array_values($rootline);

		return end($array);

	}

	// only supports html embedding
	public static function embed($context, $did = '', $class = NULL, $debug = 1) {

		//#########################################################################

			// this is a bug hotfix
			// should not be preset
		if ($context == 'dev') {
			$context = 'live';
		}

		//#########################################################################

%%switcher%%

		//#########################################################################

			// assert that variables are set up
		if (!isset($class)) { $class = 'default'; }
		if (!isset($context)) { $context = 'live'; }

		//#########################################################################

			// get the path to this includer file
		$root =  dirname(__FILE__);

			// get the include files for domain and context
		$incfiles = self::$includes[$did][$context];

			// avoid php warnings
		if (!isset($incfiles))
		{ $incfiles = array(); }

			// no debug message by default
		$debugmsg = '';

			// create a debug message to be printed out
		if ($debug) { $debugmsg = sprintf('webmerge: %s:%s:%s', $context, $did, $class); }

			// wrap debug message within a html comment if debug equals one
		if ($debug == 1) { $debugmsg = sprintf('<!-- %s -->', $debugmsg); }

			// add a newline to the debug message
		if ($debug) { $debugmsg .= "\n"; }

			// test if include for favored class exists
		if (array_key_exists($class, $incfiles)) {

				// get the include for the favored class
			return $debugmsg . self::getInclude($root . '/' . $incfiles[$class]);

			// test if include for default class exists
		} elseif (array_key_exists('default', $incfiles)) {

				// get the include for the default class
			return $debugmsg . self::getInclude($root . '/' . $incfiles['default']);

			// not a single include found
		} else {

				// give an error message as html comment
			$msg = '<!-- webmerge found no include (%s:%s:%s) -->';

				// fill in all attributes for the message
			return sprintf($msg, $context, $did, $class);

		}

		//#########################################################################

	}
	// EO fn embed

}

### END OF CLASS tx_rtpwebmerge_embed_data ###

// Add XCLASS hook
if (defined('TYPO3_MODE') && $TYPO3_CONF_VARS[TYPO3_MODE]['XCLASS']['ext/rtp_webmerge/classes/class.tx_rtpwebmerge_embed_data.php']) {
	include_once($TYPO3_CONF_VARS[TYPO3_MODE]['XCLASS']['ext/rtp_webmerge/classes/class.tx_rtpwebmerge_embed_data.php']);
}
